### ISSUE TITLE
some Problems in Libft ( Nick)

### ISSUE THREAD

**Issue by MaxIhme** [nrenz/minishell#11]
ft_strmapi.c:35:35: error: parameter 'i' set but not used 
ft_strnstr.c:20:9: error: variable 'h_len' set but not used

**Comment by MaxIhme** [comment]
or did you solve it already @RanniSch

**Comment by RanniSch** [comment]
I solved that one already. It does not work on your machine? Then we might have the issue that it did not merge.

**Comment by MaxIhme** [comment]
I thing all issues with Libft os done, right?
